# Site settings
ref: CSCC09
title: Programming on the Web
edition: Fall 2023
description: An introduction to software development on the web. Concepts underlying the development of programs that operate on the web. Operational concepts of the internet and the web, static and dynamic client content, dynamically served content, n-tiered architectures, web development processes and security on the web.
website: https://thierrysans.me/CSCC09/
github: https://github.com/ThierrySans/CSCC09
piazza: https://piazza.com/utoronto.ca/fall2023/cscc09
feedback: https://forms.gle/azbbMTq191kHhMAR6

instructor:
  name: Thierry Sans
  email: thierry.sans@utoronto.ca
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: Monday 11 AM - 12 PM 
  location: IC-346
  contact: Piazza only (no email)
  role: Prof.

# https://www.fingerlakesbmw.org/main/flobfuscate.php
assistants:
    # - name: Alexander Greff
    #   contact: "&#97;&#108;&#101;&#120;&#46;&#103;&#114;&#101;&#102;&#102;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
    #   hours: Wed 10 AM - 11 AM
    #   location: <a href="https://utoronto.zoom.us/j/87843211186">Zoom</a>
  
timings:
    - section: LEC01
      time: Wednesay 11:00-13:00
      location: MW 120
      instructor: Thierry Sans
    - section: LEC02
      time: Wednesday 14:00-16:00
      location: MW 120
      instructor: Thierry Sans
    - section: PRA01
      time: Tuesday 13:00-15:00
      location: BV 473
      instructor: TBD
    - section: PRA02
      time: Thursday 11:00-13:00
      location: BV 473
      instructor: TBD
    - section: PRA03
      time: Thursday 13:00-15:00
      location: BV 473
      instructor: TBD
    - section: PRA04
      time: Thursday 17:00-19:00
      location: BV 473
      instructor: TBD

first: 20220904