# Site settings
ref: CSCC09
title: Programming on the Web
edition: Spring 2018
description: An introduction to software development on the web. Concepts underlying the development of programs that operate on the web. Operational concepts of the internet and the web, static and dynamic client content, dynamically served content, n-tiered architectures, web development processes and security on the web.
website: https://thierrysans.github.io/CSCC09/
github: https://github.com/ThierrySans/CSCC09
piazza: https://piazza.com/mail.utoronto.ca/spring2018/cscc09
feedback: https://goo.gl/forms/n8porhFwU0ou8eOj1

instructor:
  name: Thierry Sans
  email: thierry.sans@utoronto.ca
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: Monday 3pm-5pm
  location: IC-346
  contact: Piazza only (no mail)
  # hours: Thurs 10:00am-12:00pm

assistants:
    - name: TBD
      role:  TA
      contact: #'&#101;&#100;&#111;&#117;&#097;&#114;&#100;&#046;&#109;&#097;&#103;&#104;&#097;&#114;&#105;&#097;&#110;&#064;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#046;&#099;&#097;'
      hours: by appointment
      location: ''
  
timings:
    - section: LEC01 
      time: Thursday 11:00-13:00
      location: MW 170 
    - section: PRA01
      time: Monday 13:00-14:00
      location: BV 473        
    - section: PRA02
      time: Tuesday 14:00-15:00
      location: BV 473        
    - section: PRA03
      time: Friday 11:00-12:00
      location: BV 473        
    - section: PRA04
      time: Friday 12:00-13:00
      location: BV 473
        
first: 20180108