# Site settings
ref: CSCC09
title: Programming on the Web
edition: Winter 2022
description: An introduction to software development on the web. Concepts underlying the development of programs that operate on the web. Operational concepts of the internet and the web, static and dynamic client content, dynamically served content, n-tiered architectures, web development processes and security on the web.
website: https://thierrysans.me/CSCC09/
github: https://github.com/ThierrySans/CSCC09
piazza: https://piazza.com/utoronto.ca/winter2022/cscc09
feedback: https://forms.gle/sXM23HpQT4Wjo9jX6

instructor:
  name: Thierry Sans
  email: thierry.sans@utoronto.ca
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: 11 AM - 12 PM 
  location: <a href="https://utoronto.zoom.us/j/88149611289">Zoom</a> 
  contact: Piazza only (no email)
  role: Prof.

# https://www.fingerlakesbmw.org/main/flobfuscate.php
assistants:
    - name: Alexander Greff
      contact: "&#97;&#108;&#101;&#120;&#46;&#103;&#114;&#101;&#102;&#102;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"      
      hours: TBD
      location: TBD
    - name: David Yue
      contact: "&#100;&#97;&#118;&#105;&#100;&#46;&#121;&#117;&#101;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: TBD
    - name: Rahul Ramani
      contact: "&#114;&#97;&#104;&#117;&#108;&#46;&#114;&#97;&#109;&#97;&#110;&#105;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: TBD
    - name: Lu Wei Chou
      contact: "&#112;&#101;&#116;&#101;&#114;&#46;&#99;&#104;&#111;&#117;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: TBD
    - name: Yuxuan Hu
      contact: "&#121;&#117;&#120;&#117;&#97;&#110;&#46;&#104;&#117;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: TBD
      location: TBD
  
timings:
    - section: LEC01
      time: Tuesday 12:00-14:00
      location: SW 128
      instructor: Thierry Sans
    - section: LEC02
      time: Friday 13:00-15:00
      location: SW 128
      instructor: Thierry Sans
    - section: PRA01
      time: Monday 9:00-11:00
      location: BV 473
      instructor: TBD
    - section: PRA02
      time: Monday 15:00-17:00
      location: BV 473
      instructor: TBD
    - section: PRA03
      time: Friday 9:00-11:00
      location: BV 473
      instructor: TBD
    - section: PRA04
      time: Friday 11:00-13:00
      location: BV 473
      instructor: TBD
    - section: PRA05
      time: Tuesday 10:00-12:00
      location: BV 473
      instructor: TBD
        
first: 20220110