# Site settings
ref: CSCC09
title: Programming on the Web
edition: Spring 2018
description: An introduction to software development on the web. Concepts underlying the development of programs that operate on the web. Operational concepts of the internet and the web, static and dynamic client content, dynamically served content, n-tiered architectures, web development processes and security on the web.
website: https://thierrysans.github.io/CSCC09/
github: https://github.com/ThierrySans/CSCC09
piazza: https://piazza.com/mail.utoronto.ca/spring2018/cscc09
feedback: https://goo.gl/forms/n8porhFwU0ou8eOj1

instructor:
  name: Thierry Sans
  email: thierry.sans@utoronto.ca
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: TBD
  location: IC-346
  contact: Piazza only (no mail)

assistants:
    - name: TBD
      role:  TA
      contact: TBD #'&#101;&#100;&#111;&#117;&#097;&#114;&#100;&#046;&#109;&#097;&#103;&#104;&#097;&#114;&#105;&#097;&#110;&#064;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#046;&#099;&#097;'
      hours: TBD
      location: TBD
  
timings:
    - section: LEC01 
      time: Monday 11:00-12:00
      location: MW 160 
    - section: 
      time: Friday 11:00-13:00
      location: HW 214 
    - section: LEC02
      time: Monday 13:00-15:00
      location: IC 220 
    - section: 
      time: Friday 14:00-15:00
      location: MV 160
    - section: PRA01
      time: Monday 9:00-11:00
      location: BV 473        
    - section: PRA02
      time: Monday 15:00-17:00
      location: BV 473        
    - section: PRA03
      time: Friday 9:00-11:00
      location: BV 473        
    - section: PRA04
      time: Thursday 18:00-20:00
      location: BV 473
        
first: 20180108