# Site settings
ref: CSCC09
title: Programming on the Web
edition: Fall 2023
description: An introduction to software development on the web. Concepts underlying the development of programs that operate on the web. Operational concepts of the internet and the web, static and dynamic client content, dynamically served content, n-tiered architectures, web development processes and security on the web.
website: https://thierrysans.me/CSCC09/
github: https://github.com/ThierrySans/CSCC09
piazza: https://piazza.com/utoronto.ca/fall2023/cscc09
feedback: https://forms.gle/azbbMTq191kHhMAR6

instructor:
  name: Thierry Sans
  email: thierry.sans@utoronto.ca
  website: https://thierrysans.github.io/
  github: ThierrySans
  twitter: ThierrySans
  hours: Monday 11 AM - 12 PM 
  location: IC-346
  contact: Piazza only (no email)
  role: Prof.

# https://www.fingerlakesbmw.org/main/flobfuscate.php
assistants:
    - name: Lazar Glumac
      contact: "&#108;&#97;&#122;&#97;&#114;&#46;&#103;&#108;&#117;&#109;&#97;&#99;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Wed 11:00-12:00
      location: TBD
    - name: Yuqi (Amy) Liang
      contact: "&#97;&#109;&#121;&#46;&#108;&#105;&#97;&#110;&#103;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Tue 14:00-15:00
      location: TBD
    - name: Aum Himendu Patel
      contact: "&#97;&#117;&#109;&#46;&#112;&#97;&#116;&#101;&#108;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Thur 19:00-20:00
      location: TBD
    - name: Benjamin Saobuppha
      contact: "&#98;&#101;&#110;&#46;&#115;&#97;&#111;&#98;&#117;&#112;&#112;&#104;&#97;&#64;&#109;&#97;&#105;&#108;&#46;&#117;&#116;&#111;&#114;&#111;&#110;&#116;&#111;&#46;&#99;&#97;"
      hours: Fri
      location: 19:00-20:00
  
timings:
    - section: LEC01
      time: Wednesay 11:00-13:00
      location: MW 120
      instructor: Thierry Sans
    - section: LEC02
      time: Wednesday 14:00-16:00
      location: MW 110
      instructor: Thierry Sans
    - section: PRA01
      time: Tuesday 13:00-15:00
      location: BV 473
      instructor: Lazar Glumac
    - section: PRA02
      time: Thursday 11:00-13:00
      location: BV 473
      instructor: Aum Himendu Patel
    - section: PRA03
      time: Thursday 13:00-15:00
      location: BV 473
      instructor: Yuqi (Amy) Liang
    - section: PRA04
      time: Thursday 17:00-19:00
      location: BV 473
      instructor: Benjamin Saobuppha

first: 20230904